name: santai
version: 1.0.0+4
publish_to: none
description: Santai Technology.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  mutex: ^3.1.0
  flutter_background_service: ^2.4.1
  flutter_background_service_android: ^3.0.3
  syncfusion_flutter_datepicker: ^20.2.49
  shimmer: ^2.0.0
  overlay_support: ^1.2.1
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  lottie: ^2.2.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  device_info_plus: 10.1.2
  dio: ^5.7.0
  dropdown_search: 5.0.6
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.2.0
  number_paginator: ^0.4.1
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_chat_types: 3.6.2
  flutter_chat_ui: 1.6.15
  flutter_svg: ^1.1.6 
  emoji_picker_flutter: ^3.1.0
  flutter_local_notifications: 17.2.2
  flutter_secure_storage: 9.2.2
  flutter_timezone: ^3.0.1
  fluttertoast: 8.2.8
  geocoding: 3.0.0
  geolocator: ^12.0.0
  get: 4.6.6
  google_maps_flutter: 2.10.0
  google_place: ^0.4.7
  google_sign_in: 6.2.1
  http: ^0.13.3
  http_parser: ^4.0.2
  image_picker: 1.1.2
  intl: 0.19.0
  intl_phone_field: 3.2.0
  path: 1.9.0
  permission_handler: 11.3.1
  shared_preferences: 2.3.2
  signalr_core: ^1.1.1
  sqflite: 2.3.3+1
  timeline_tile: 2.0.0
  timezone: ^0.9.4
  uuid: ^4.5.0
  webview_flutter: 4.8.0 
  url_launcher: ^6.1.8
  flutter_markdown: ^0.7.4+3
  marquee: ^2.3.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/  
    - assets/icons/
    - assets/animations/ 
  fonts:
    - family: Saira
      fonts: 
        - asset: assets/fonts/sairas/Saira-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira-Black.ttf
          weight: 900
    - family: SairaCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_Condensed-Black.ttf
          weight: 900
    - family: SairaSemiCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Black.ttf
          weight: 900
    - family: SairaExtraCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Black.ttf
          weight: 900
    - family: SairaUltraCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_UltraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_UltraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_UltraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Black.ttf
          weight: 900
    - family: SairaExpanded
      fonts:
        - asset: assets/fonts/sairas/Saira_Expanded-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_Expanded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_Expanded-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_Expanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_Expanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_Expanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_Expanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_Expanded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_Expanded-Black.ttf
          weight: 900
  uses-material-design: true

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/images/logo_santaimoto_bluesquare.png
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
