name: santai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  image_picker: 1.1.2
  geolocator: 13.0.1
  geocoding: 3.0.0
  webview_flutter: 4.8.0
  http: 1.2.2
  flutter_chat_ui: 1.6.15
  flutter_chat_types: 3.6.2
  uuid: 4.4.2
  intl_phone_field: 3.2.0
  google_sign_in: 6.2.1
  intl: 0.19.0
  flutter_secure_storage: 9.2.2
  device_info_plus: 10.1.2
  sqflite: 2.3.3+1
  path: 1.9.0
  shared_preferences: 2.3.2
  timezone: 0.9.4
  permission_handler: 11.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/splash_image.png
    - assets/images/google_logo.png
  fonts: 
    - family: Saira
      fonts: 
        - asset: assets/fonts/saira/Saira-Regular.ttf
          weight: 400
        - asset: assets/fonts/saira/Saira-Bold.ttf
          weight: 600
  uses-material-design: true

