name: santai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  image_picker: 1.1.2
  geolocator: 13.0.1
  geocoding: 3.0.0
  webview_flutter: 4.8.0
  http: 1.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/splash_image.png
  uses-material-design: true

